# SPDX-License-Identifier: CC0-1.0

language = 'Erlang'
display = 'Erlang (Erlang 28.0.2)'
license = [
    { name = 'Apache-2.0', url = 'https://github.com/erlang/otp/blob/master/LICENSE.txt' },
]

filename = 'Main.erl'

install = '''
AC_OTP_VERSION=28.0.2
sudo apt-get update
sudo apt-get install -y libssl-dev unixodbc-dev

cd /tmp
wget -q -O erlang.tar.gz https://github.com/erlang/otp/releases/download/OTP-${AC_OTP_VERSION}/otp_src_${AC_OTP_VERSION}.tar.gz
mkdir erlang
tar -C erlang --strip-components=1 -xf erlang.tar.gz
cd erlang
./configure --without-termcap
make -j$(nproc)
sudo make install
'''

compile = '''
erlc Main.erl 1>&2
'''

object = 'Main.beam'

execution = [
    'erl',
    '-noshell',
    '-run',
    'Main',
    'main',
    'run',
]
