# SPDX-License-Identifier: CC0-1.0

language = 'PHP'
display = 'PHP (PHP 8.4.12)'
license = [{ name = 'PHP-3.01', url = 'https://www.php.net/license/' }]
library.php-bcmath = { license = [
    { name = 'LGPL-2.1-or-later', url = 'https://github.com/php/php-src/tree/PHP-8.4.12/ext/bcmath/libbcmath' },
], version = 'v8.4.12' }
library.php-gmp = { license = [
    { name = 'PHP-3.01', url = 'https://github.com/php/php-src/blob/PHP-8.4.12/ext/gmp/gmp.c'}
], version = 'v8.4.12' }
library.php-sqlite3 = { license = [
    { name = 'PHP-3.01', url = 'https://github.com/php/php-src/blob/PHP-8.4.12/ext/sqlite3/sqlite3.c' }
], version = 'v8.4.12' }
library.gmp = { license = [
    { name = 'LGPL-3.0-or-later', url = 'https://gmplib.org/repo/gmp-6.3/file/tip/README' },
    { name = 'GPL-2.0-or-later', url = 'https://gmplib.org/repo/gmp-6.3/file/tip/README' },
], version = '6.3.0', indirect = true }
library.sqlite3 = { license = [
    { name = 'blessing', url = 'https://www.sqlite.org/copyright.html' },
], version = '3.45.1', indirect = true }
filename = 'Main.php'
install = '''
sudo apt update
DEBIAN_FRONTEND=noninteractive sudo -E apt -y install software-properties-common
sudo add-apt-repository -y ppa:ondrej/php
sudo apt update
DEBIAN_FRONTEND=noninteractive sudo -E apt install -y php8.4-cli php8.4-gmp php8.4-bcmath php8.4-sqlite3
echo "opcache.enable_cli = 1
opcache.jit = tracing
opcache.jit_buffer_size = 128M
" | sudo tee -a /etc/php/8.4/cli/conf.d/10-opcache.ini
'''
compile = '''
php -l Main.php && touch a.out && php Main.php ONLINE_JUDGE 2> /dev/null
'''
object = 'a.out'
execution = [
    'php',
    'Main.php',
]
