[profile.release]
lto = true # コンパイル時間が著しく長くなってしまう場合は無し

[package]
name = "main"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
# Essential competitive programming libraries only
ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs", rev = "89356739594fa35cb744f374bfb68a2eb27a64ae" }
proconio = { version = "=0.5.0", features = ["derive"] }
rustc-hash = "=2.1.1"
smallvec = { version = "=1.15.0", features = ["const_generics", "const_new", "write", "union", "serde", "arbitrary"] }
once_cell = "=1.21.3"

# Lightweight essential libraries
bitvec = "=1.0.1"
fixedbitset = "=0.5.7"
bitset-fixed = "=0.1.0"
counter = "=0.6.0"
gcd = "=2.3.0"
text_io = "=0.1.13"
static_assertions = "=1.1.0"
thiserror = "=2.0.12"

# Basic data structures
btreemultimap = "=0.1.1"
multimap = "=0.10.1"
indexmap = "=2.2.6"
bstr = "=1.12.0"
az = "=1.2.1"

# Mathematical essentials only
primal = "=0.3.3"
rand_xorshift = "=0.4.0"
rand_xoshiro = "=0.7.0"

# Removed heavy libraries:
# - statrs (statistical functions)
# - varisat (SAT solver)  
# - pathfinding (graph algorithms)
# - amplify family (large multi-purpose library)
# - im-rc (immutable collections)
# - memoise (memoization)
# - argio (argument parsing)
# - recur-fn (recursion utilities)
# - hashbag (hash-based multiset)