name: Build PR
on:
  pull_request:
    branches:
      - main

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          platforms: linux/amd64
          load: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/atcoder-container:latest
